### ISSUE TITLE
JsonObject / JSONObject

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-rap#24]
OlObject (and maybe other classes) uses **org.eclipse.rap.json.JsonObject**. If there is no good reason to do so, it would be better to use **org.json.JSONObject** for compatibility with other code. Pros / Cons?

**Comment by stundzig** [comment]
The main part of the openlayers wrapper is the communication with the JS part. This is done via rap.RemoteObject and the main class there is org.eclipse.rap.rwt.remote.AbstractOperationHandler. But the handler itself uses JsonObject in its method signature. Therefore i've used it also in the other Ol* classes too. Otherwise i must transform the JsonObject from/to the rap.RemoteObject anytime.

**Comment by stundzig** [comment]
*org.eclipse.rap.json.JsonObject* is used only internally, in all APIs now we have *org.json.JSONObject*.

**Comment by stundzig** [comment]
BREAKING CHAGE: All usages of org.polymap.rap.openlayers.base.OlEvent.properties must be changed from rap.JsonObject to the new org.json.JSONObject.
